# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: piper.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpiper.proto\x12\x05piper\"\x83\x01\n\x17SynthesizeSpeechRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\x12*\n\x05voice\x18\x02 \x01(\x0b\x32\x1b.piper.VoiceSelectionParams\x12(\n\x0c\x61udio_config\x18\x03 \x01(\x0b\x32\x12.piper.AudioConfig\"?\n\x14VoiceSelectionParams\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12\x10\n\x08voice_id\x18\x02 \x01(\t\"V\n\x0b\x41udioConfig\x12,\n\x0e\x61udio_encoding\x18\x01 \x01(\x0e\x32\x14.piper.AudioEncoding\x12\x19\n\x11sample_rate_hertz\x18\x02 \x01(\x05\"1\n\x18SynthesizeSpeechResponse\x12\x15\n\raudio_content\x18\x01 \x01(\x0c\"\x15\n\x13GetLanguagesRequest\":\n\x14GetLanguagesResponse\x12\"\n\tlanguages\x18\x01 \x03(\x0b\x32\x0f.piper.Language\"C\n\x08Language\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x10\n\x08iso_code\x18\x02 \x01(\t\x12\x13\n\x0blanguage_id\x18\x03 \x01(\t\"\'\n\x10GetVoicesRequest\x12\x13\n\x0blanguage_id\x18\x01 \x01(\t\"1\n\x11GetVoicesResponse\x12\x1c\n\x06voices\x18\x01 \x03(\x0b\x32\x0c.piper.Voice\"-\n\x05Voice\x12\x10\n\x08voice_id\x18\x01 \x01(\t\x12\x12\n\nvoice_name\x18\x02 \x01(\t*_\n\rAudioEncoding\x12\x1e\n\x1a\x41UDIO_ENCODING_UNSPECIFIED\x10\x00\x12\x0c\n\x08LINEAR16\x10\x01\x12\t\n\x05MULAW\x10\x02\x12\x07\n\x03MP3\x10\x03\x12\x0c\n\x08OGG_OPUS\x10\x04\x32\xde\x01\n\x02gw\x12O\n\nSynthesize\x12\x1e.piper.SynthesizeSpeechRequest\x1a\x1f.piper.SynthesizeSpeechResponse0\x01\x12G\n\x0cGetLanguages\x12\x1a.piper.GetLanguagesRequest\x1a\x1b.piper.GetLanguagesResponse\x12>\n\tGetVoices\x12\x17.piper.GetVoicesRequest\x1a\x18.piper.GetVoicesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'piper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOENCODING']._serialized_start=651
  _globals['_AUDIOENCODING']._serialized_end=746
  _globals['_SYNTHESIZESPEECHREQUEST']._serialized_start=23
  _globals['_SYNTHESIZESPEECHREQUEST']._serialized_end=154
  _globals['_VOICESELECTIONPARAMS']._serialized_start=156
  _globals['_VOICESELECTIONPARAMS']._serialized_end=219
  _globals['_AUDIOCONFIG']._serialized_start=221
  _globals['_AUDIOCONFIG']._serialized_end=307
  _globals['_SYNTHESIZESPEECHRESPONSE']._serialized_start=309
  _globals['_SYNTHESIZESPEECHRESPONSE']._serialized_end=358
  _globals['_GETLANGUAGESREQUEST']._serialized_start=360
  _globals['_GETLANGUAGESREQUEST']._serialized_end=381
  _globals['_GETLANGUAGESRESPONSE']._serialized_start=383
  _globals['_GETLANGUAGESRESPONSE']._serialized_end=441
  _globals['_LANGUAGE']._serialized_start=443
  _globals['_LANGUAGE']._serialized_end=510
  _globals['_GETVOICESREQUEST']._serialized_start=512
  _globals['_GETVOICESREQUEST']._serialized_end=551
  _globals['_GETVOICESRESPONSE']._serialized_start=553
  _globals['_GETVOICESRESPONSE']._serialized_end=602
  _globals['_VOICE']._serialized_start=604
  _globals['_VOICE']._serialized_end=649
  _globals['_GW']._serialized_start=749
  _globals['_GW']._serialized_end=971
# @@protoc_insertion_point(module_scope)
